# -*- coding: utf-8 -*-
{
    'name': "lavish_hr_employee",
    'summary': """
        Módulo de nómina para la localización colombiana | Prametrización & Hoja de Vida Empleado & Contrato""",
    'description': """
        Módulo de nómina para la localización colombiana | Prametrización &  Hoja de Vida Empleado & Contrato      
    """,
    'author': "Lavish S.A.S",
    'category': 'Human Resources',
    'version': '19.0.1.39',
    'external_dependencies': {
        'python': ['dateutil', 'numpy', 'pandas', 'PyPDF2', 'pytz', 'xlsxwriter'],
    },
    'license': 'OPL-1',
    'depends': [
        'base',
        'documents',
        'lavish_erp',
        'hr',
        'hr_skills',
        'hr_payroll',
        'hr_contract',
        'hr_holidays',
        'hr_payroll_account',
        'lavish_hr_work_entry_gantt',
        'hr_org_chart',
        'stock',
        'purchase',
    ],
    "data": [
        "views/hr_indicador_especial_pila_views.xml",
        "data/hr_indicador_especial_pensiones_data.xml",
        "data/hr_tipos_cotizante_data.xml",
       # "data/hr_parameterization_data.xml",
        "data/hr_types_employee_data.xml",
        "data/account_account_type_data.xml",
        # "data/hr_certificate_income_data.xml",  # deshabilitado: líneas plantilla sin header_id/name (requeridos) -> NotNullViolation; data muerto, sin referencias
        "data/epp_dotacion/ir_cron_epp.xml",
        "data/epp_batch/ir_sequence_batch.xml",
        "data/epp_batch/mail_template_epp.xml",
        "data/hr_contract_type_data.xml",  # Tipos de Contrato Ley 2466/2025
        "security/hr_security.xml",
        "security/ir_rule.xml",
        "security/ir.model.access.csv",
        "views/hr_contract_change_wage_views.xml",
        "views/hr_contractual_modifications_views.xml",
        "views/actions_contract.xml",
        "views/actions_employee_report_curriculum.xml",
        "views/actions_employee.xml",
        "views/hr_employee_skills_override.xml",
        "views/actions_entities.xml",
        "views/actions_hr_salary_history_report.xml",
        "views/actions_labor_certificate_history.xml",
        "views/actions_labor_certificate_template.xml",
        "views/actions_parameterization_of_contributors.xml",
        "views/actions_parametrization.xml",
        "views/actions_partner_employee.xml",
        "views/actions_retirement_severance_pay.xml",
        "views/actions_salary_rule.xml",
        "views/entidade_empleados.xml",
        # Nuevas vistas para certificado de ingresos y retenciones
        "views/hr_certificate_income_config_views.xml",
        "wizard/hr_certificate_income_wizard_views.xml",
        "report/report_change_wage_template.xml",
        "report/report_change_wage.xml",
        "data/mail_template_change_wage.xml",  # Plantilla email cambio salarial (despues del reporte)
        "report/report_birthday_list_template.xml",
        "report/report_birthday_list.xml",
        "report/report_certification_template.xml",
        "report/report_certification.xml",
        "report/report_personal_data_form_template.xml",
        "report/report_personal_data_form.xml",
        "report/report_print_badge_template.xml",
        "report/report_print_badge.xml",
        "report/report_retirement_severance_pay_template.xml",
        "report/report_retirement_severance_pay.xml",
        "report/epp_dotacion/report_epp_delivery.xml",
        "report/medical/report_medical_certificate.xml",
        "report/report_epp_request_formal.xml",
        "report/epp_batch/report_batch_delivery.xml",
        "report/epp_batch/report_batch_stock_moves.xml",
        "wizard/wizard_mass_epp_request_views.xml",
        "views/epp_dotacion_views.xml",
        "views/epp_dotacion_menu.xml",
        "views/epp_batch/hr_epp_batch_views.xml",
        "views/epp_batch/wizard_epp_batch_generate_views.xml",
        "views/hr_loan_request_views.xml",
        "views/hr_loan_inherit_views.xml",
        # Configuración Unificada Nómina CO
        "wizard/hr_annual_parameters_copy_wizard_views.xml",
        "views/res_config_settings_nomina_views.xml",
        # Sistema Flexible de Construccion de Cuentas Contables
        "views/hr_accounting_structure_views.xml",
        "views/hr_contract_type_views.xml",  # Tipos de Contrato Ley 2466/2025
        "views/hr_deduction_priority_views.xml",  # Prioridad de deducciones limite 50%
        "views/menus/certificates_actions.xml",
        "views/menus/config_actions.xml",
        "views/menus/contract_actions.xml",
        "views/menus/employee_actions.xml",
        "views/menus/epp_actions.xml",
        "views/menus/medical_actions.xml",
        "views/menus/payroll_actions.xml",
        "views/menus.xml",
    ],
    'installable': True,
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
}
