# -*- coding: utf-8 -*-
from . import utils
from . import resource_calendar
from . import hr_period
from . import hr_employee_salary_history
from . import hr_employee_ibc_history
from . import hr_slip_data_structures
from . import hr_slip_constante
from . import hr_slip_acumulacion
from . import hr_payslip_worked_days

# Modelos de nomina separados
from . import hr_absence_days
from . import hr_payslip_day
from . import hr_payslip_not_line
from . import hr_payslip_rule_override

from . import account_journal
from . import hr_leave
from . import hr_vacation
from . import hr_cesantias
from . import hr_prima
from . import hr_contrato
from . import hr_payroll
from . import hr_payroll_other
from . import hr_payroll_account_move
from . import res_company
from . import res_config_settings
from . import hr_loans
from . import hr_overtime
from . import hr_payroll_flat_file
from . import lavish_payroll_flat_file_backup
from . import hr_voucher_sending
from . import hr_novelties_different_concepts
from . import hr_novelties_independents
from . import hr_payroll_posting
from . import hr_accumulated_payroll
from . import hr_work_entry
from . import hr_contract
from . import hr_payroll_base_values_excel
from . import hr_absence_history
from . import res_partner
from . import hr_transfers_of_entities
from . import hr_slip
from . import hr_payslip_line
from . import hr_payroll_dashboard
from . import hr_dashboard_layout
from . import hr_payslip_run
from . import hr_salary_rule_loans
from . import hr_payslip_number
from . import mixin_rule_extra_logic
from . import hr_payroll_epp
from . import services
from . import hr_payroll_structure_section
from . import hr_salary_increase
from . import hr_payslip_line_viewer
from . import hr_payslip_line_report
from . import hr_payslip_lines_grid_report
from . import lavish_xml_generator
from . import advance
from . import browsable_object_EE
from . import browsable_object
from . import dian_payroll_document
from . import hr_accumulated_reports
from . import hr_calculation_rtefte_ordinary
from . import hr_compute_engine
from . import hr_concepts_deduction_retention
from . import hr_electronic_adjust_payroll
from . import hr_electronic_payroll
from . import hr_leave_new
from . import hr_payroll_dashboard_optimized
from . import hr_payroll_hours
from . import hr_payroll_novedades
from . import hr_payslip_analytic_distribution
from . import hr_slip_visual
from . import lavis_erp_utilario_payroll
from . import salary_rules
